apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-provider-restapi
  description: A Terraform provider for REST API calls as configuration objects
  links:
    - url: https://registry.terraform.io/providers/Jimdo/restapi
      title: Terraform Registry Page
      icon: ExitToApp
  annotations:
    github.com/project-slug: Jimdo/terraform-provider-restapi
    github.com/team-slug: Jimdo/devex
    backstage.io/techdocs-ref: "dir:."
  tags:
    - terraform
    - provider
    - restapi
    - infra
spec:
  type: service
  owner: devex
  lifecycle: staging
